site_url: https://travel-blog.isaachsmith.info/
logo_url: https://travel-blog.isaachsmith.info/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
media_library:
  name: cloudinary
  config:
    cloud_name: dfkk9455p
    api_key: 543775587292518

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'assets/content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
  - label: 'Journal Entries'
    label_singular: 'Journal Entry'
    name: 'journal_entry'
    folder: 'assets/content/adventures'
    path: '{{adventure.slug}}/{{slug}}'
    create: true
    format: 'json'
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: 'Adventure'
        name: 'adventure'
        widget: 'relation'
        collection: 'adventures'
        value_field: '{{slug}}'
        search_fields: ['title', 'description', 'content']
        display_fields: ['title']
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Cover Image', name: 'cover', widget: 'image', allow_multiple: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'adventures'
    label: 'Adventures'
    label_singular: 'Adventure'
    folder: 'assets/content/adventures'
    create: true
    format: 'json'
    slug: '{{slug}}'
    preview_path: 'adventures/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Cover Image', name: 'cover', widget: 'image', allow_multiple: false }
      - label: 'Adventure Dates'
        name: 'dates'
        widget: 'object'
        summary: 'The dates for the adventure'
        fields:
          - { label: 'Start Date', name: 'start', widget: 'datetime' }
          - { label: 'End Date', name: 'end', widget: 'datetime', required: false }